version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  web:
    image: django:latest
    container_name: django_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb
    working_dir: /app
    networks:
      - app-network
    command: /bin/sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:

networks:
  app-network:
      driver: bridge
