# Generated by Django 5.2.4 on 2025-07-14 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lista_vendedores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.CharField(max_length=150)),
                (
                    "servico",
                    models.CharField(
                        choices=[
                            ("SL", "Solar"),
                            ("LT", "Loteamento"),
                            ("PDE", "PDE"),
                            ("HD", "Hidraulico"),
                        ],
                        max_length=15,
                    ),
                ),
                ("telefone", models.CharField(max_length=15)),
                ("cidade", models.CharField(blank=True, max_length=150, null=True)),
                ("consumo", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "comissao",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("Janeiro", "Jan"),
                            ("Fevereiro", "Fev"),
                            ("Março", "Mar"),
                            ("Abril", "Abr"),
                            ("Maio", "Mai"),
                            ("Junho", "Jun"),
                            ("Julho", "Jul"),
                            ("Agosto", "Ago"),
                            ("Setembro", "Set"),
                            ("Outubro", "Out"),
                            ("Novembro", "Nov"),
                            ("Dezembro", "Dez"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ano", models.CharField(blank=True, max_length=4)),
                (
                    "status_venda",
                    models.CharField(
                        choices=[
                            ("env_banc", "Enviado ao banco"),
                            ("aprov_banc", "Banco aprovado"),
                            ("repr_banc", "Banco reprovado"),
                            ("cancel_banc", "Banco cancelado"),
                            ("cancel_client", "Cliente cancelado"),
                        ],
                        default="env_banc",
                        max_length=15,
                    ),
                ),
                (
                    "status_pg_vendedor",
                    models.CharField(
                        choices=[
                            ("agr_vd", "Aguardando venda"),
                            ("agr_banc", "Aguardando o banco"),
                            ("real", "Realizado"),
                            ("pend", "Pendente"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="agr_vd",
                        max_length=15,
                    ),
                ),
                ("foto_documento", models.FileField(upload_to="documentos/")),
                ("foto_endereco", models.FileField(upload_to="documentos/")),
                ("foto_contracheque", models.FileField(upload_to="documentos/")),
                (
                    "proposta",
                    models.FileField(blank=True, null=True, upload_to="documentos/"),
                ),
                (
                    "contrato",
                    models.FileField(blank=True, null=True, upload_to="documentos/"),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venda",
                        to="lista_vendedores.listavendedores",
                    ),
                ),
            ],
        ),
    ]
