# Generated by Django 5.1.5 on 2025-01-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150)),
                ('servico', models.CharField(choices=[('Solar', 'SL'), ('Loteamento', 'LT'), ('PDE', 'PDE'), ('Hidraulico', 'HD')], max_length=15)),
                ('telefone', models.CharField(max_length=15)),
                ('consumo', models.CharField(blank=True, max_length=30, null=True)),
                ('valor', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('vendendor', models.CharField(blank=True, max_length=150)),
                ('foto_documento', models.FileField(upload_to='documentos/')),
                ('foto_endereco', models.FileField(upload_to='documentos/')),
                ('foto_contracheque', models.FileField(upload_to='documentos/')),
            ],
        ),
    ]
