# Generated by Django 5.1.5 on 2025-01-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='servico',
            field=models.CharField(choices=[('SL', 'Solar'), ('LT', 'Loteamento'), ('PDE', 'PDE'), ('HD', 'Hidraulico')], max_length=15),
        ),
    ]
