# Generated by Django 5.1.5 on 2025-01-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_remove_venda_comissao_alter_venda_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
