# Generated by Django 5.1.5 on 2025-01-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_venda_status_pg_vendedor_venda_status_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status_pg_vendedor',
            field=models.CharField(choices=[('agr_vd', 'Aguardando venda'), ('agr_banc', 'Aguardando o banco'), ('real', 'Realizado'), ('pend', 'Pendente'), ('Cancelado', 'Cancelado')], default='agr_vd', max_length=15),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status_venda',
            field=models.CharField(choices=[('env_banc', 'Enviado ao banco'), ('aprov_banc', 'Banco aprovado'), ('repr_banc', 'Banco reprovado'), ('cancel_banc', 'Banco cancelado'), ('cancel_client', 'Cliente cancelado')], default='env_banc', max_length=15),
        ),
    ]
