# Generated by Django 5.1.5 on 2025-01-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0009_venda_contrato_venda_proposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='contrato',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='proposta',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
