# Generated by Django 5.1.5 on 2025-01-28 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_vendedores', '0001_initial'),
        ('vendas', '0010_alter_venda_contrato_alter_venda_proposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='vendendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venda', to='lista_vendedores.listavendedores'),
        ),
    ]
