# Generated by Django 5.1.5 on 2025-01-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0015_venda_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='mes',
            field=models.CharField(choices=[('January', 'Jan'), ('February', 'Feb'), ('March', 'Mar'), ('April', 'Apr'), ('May', 'May'), ('June', 'Jun'), ('July', 'Jul'), ('August', 'Aug'), ('September', 'Sep'), ('October', 'Oct'), ('November', 'Nov'), ('December', 'Dec')], max_length=10),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
