# Generated by Django 5.1.5 on 2025-02-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0016_alter_venda_mes_alter_venda_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='mes',
            field=models.CharField(choices=[('Janeiro', 'Jan'), ('Fevereiro', 'Feb'), ('Marco', 'Mar'), ('Abril', 'Apr'), ('maio', 'May'), ('Junho', 'Jun'), ('Julho', 'Jul'), ('Agosto', 'Aug'), ('Setembro', 'Sep'), ('Outubro', 'Oct'), ('Novembro', 'Nov'), ('Dezembro', 'Dec')], max_length=10),
        ),
    ]
