# Generated by Django 5.2.4 on 2025-07-14 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lista_vendedores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cliente",
                    models.CharField(max_length=150, verbose_name="Nome do cliente"),
                ),
                ("telefone", models.CharField(max_length=15)),
                (
                    "tipo_serviço",
                    models.CharField(
                        choices=[
                            ("Eng_Solar", "Energia solar"),
                            ("LT", "Loteamento"),
                            ("PDE", "PDE"),
                            ("HD", "Hidraulica"),
                        ],
                        default="Eng_Solar",
                        max_length=14,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("V", "Visita"),
                            ("I", "Iniciado"),
                            ("Co", "Contrato"),
                            ("A", "Andamento"),
                            ("E", "Execucao"),
                            ("C", "Concluido"),
                            ("P", "Pendente"),
                        ],
                        default="V",
                        max_length=10,
                    ),
                ),
                ("cidade", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "valor_empreendimento",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "valor_custos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "valor_lucro",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("Janeiro", "Jan"),
                            ("Fevereiro", "Fev"),
                            ("Março", "Mar"),
                            ("Abril", "Abr"),
                            ("Maio", "Mai"),
                            ("Junho", "Jun"),
                            ("Julho", "Jul"),
                            ("Agosto", "Ago"),
                            ("Setembro", "Set"),
                            ("Outubro", "Out"),
                            ("Novembro", "Nov"),
                            ("Dezembro", "Dez"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ano", models.CharField(blank=True, max_length=4)),
                ("foto_documento", models.FileField(upload_to="documentos/")),
                ("comoprovante_endereco", models.FileField(upload_to="documentos/")),
                ("comoprovante_renda", models.FileField(upload_to="documentos/")),
                ("projeto_ativo", models.BooleanField(default=True)),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lista_vendedores.listavendedores",
                    ),
                ),
            ],
        ),
    ]
