# Generated by Django 5.1.5 on 2025-02-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0009_alter_servico_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='projeto_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
