# Generated by Django 5.1.5 on 2025-06-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servico", "0010_servico_projeto_ativo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servico",
            name="cliente",
            field=models.CharField(max_length=150, verbose_name="Nome do cliente"),
        ),
        migrations.AlterField(
            model_name="servico",
            name="valor_custos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="servico",
            name="valor_lucro",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
