# Generated by Django 5.1.5 on 2025-01-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_venda_comissao_alter_venda_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='comissao',
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
