# Generated by Django 5.1.5 on 2025-01-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_venda_comissao_alter_venda_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status_pg_vendedor',
            field=models.CharField(choices=[('agr_banc', 'Aguardando o banco'), ('real', 'Realizado'), ('pend', 'Pendente'), ('Cancelado', 'Cancelado')], default='1', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='status_venda',
            field=models.CharField(choices=[('env_banc', 'Enviado ao banco'), ('aprov_banc', 'Banco aprovado'), ('repr_banc', 'Banco reprovado'), ('cancel_banc', 'Banco cancelado'), ('cancel_client', 'Cliente cancelado')], default='2', max_length=15),
            preserve_default=False,
        ),
    ]
