# Generated by Django 5.1.5 on 2025-01-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_alter_venda_status_pg_vendedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='ano',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='venda',
            name='mes',
            field=models.CharField(choices=[('Jan', 'Jan'), ('Fev', 'Fev'), ('Mar', 'Mar'), ('Abr', 'Abr'), ('Mai', 'Mai'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Ago', 'Ago'), ('Set', 'Set'), ('Out', 'Out'), ('Nov', 'Nov'), ('Dez', 'Dez')], default='Set', max_length=4),
            preserve_default=False,
        ),
    ]
