# Generated by Django 5.1.5 on 2025-01-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_venda_ano_venda_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='contrato',
            field=models.FileField(default=1, upload_to='documentos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='proposta',
            field=models.FileField(default='1', upload_to='documentos/'),
            preserve_default=False,
        ),
    ]
