# Generated by Django 5.1.5 on 2025-01-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0011_alter_venda_vendendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='vendendor',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
