# Generated by Django 5.1.5 on 2025-01-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0013_alter_venda_vendendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='vendendor',
            new_name='vendedor',
        ),
    ]
