# Generated by Django 5.1.5 on 2025-01-31 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0014_rename_vendendor_venda_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cidade',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
