# Generated by Django 5.1.5 on 2025-02-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0018_alter_venda_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='mes',
            field=models.CharField(choices=[('Janeiro', 'Jan'), ('Fevereiro', 'Fev'), ('Março', 'Mar'), ('Abril', 'Abr'), ('Maio', 'Mai'), ('Junho', 'Jun'), ('Julho', 'Jul'), ('Agosto', 'Ago'), ('Setembro', 'Set'), ('Outubro', 'Out'), ('Novembro', 'Nov'), ('Dezembro', 'Dez')], max_length=10),
        ),
    ]
