# Generated by Django 5.1.5 on 2025-01-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=15)),
                ('tipo_serviço', models.CharField(choices=[('Eng_Solar', 'Energia solar'), ('LT', 'Loteamento'), ('PDE', 'PDE'), ('HD', 'Hidraulica')], default='Eng_Solar', max_length=14)),
                ('status', models.CharField(choices=[('V', 'Visita'), ('I', 'Iniciado'), ('Co', 'Contrato'), ('A', 'Andamento'), ('E', 'Execucao'), ('C', 'Concluido'), ('P', 'Pendente')], default='V', max_length=4)),
                ('valor_empreendimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_custos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_lucro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('foto_documento', models.FileField(upload_to='documentos/')),
                ('comoprovante_endereco', models.FileField(upload_to='documentos/')),
                ('comoprovante_renda', models.FileField(upload_to='documentos/')),
            ],
        ),
    ]
