# Generated by Django 5.1.5 on 2025-01-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='ano',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='servico',
            name='mes',
            field=models.CharField(choices=[('Jan', 'Jan'), ('Fev', 'Fev'), ('Mar', 'Mar'), ('Abr', 'Abr'), ('Mai', 'Mai'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Ago', 'Ago'), ('Set', 'Set'), ('Out', 'Out'), ('Nov', 'Nov'), ('Dez', 'Dez')], default='jun', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servico',
            name='status',
            field=models.CharField(choices=[('Visita', 'V'), ('Iniciado', 'I'), ('Contrato', 'Co'), ('Andamento', 'A'), ('Execucao', 'E'), ('Concluido', 'C'), ('Pendente', 'P')], default='V', max_length=10),
        ),
    ]
