# Generated by Django 5.1.5 on 2025-01-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_servico_ano_servico_mes_alter_servico_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='mes',
            field=models.CharField(choices=[('Janeiro', 'Jan'), ('Fev', 'Fev'), ('Mar', 'Mar'), ('Abr', 'Abr'), ('Mai', 'Mai'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Ago', 'Ago'), ('Set', 'Set'), ('Out', 'Out'), ('Nov', 'Nov'), ('Dez', 'Dez')], max_length=10),
        ),
        migrations.AlterField(
            model_name='servico',
            name='status',
            field=models.CharField(choices=[('V', 'Visita'), ('I', 'Iniciado'), ('Co', 'Contrato'), ('A', 'Andamento'), ('E', 'Execucao'), ('C', 'Concluido'), ('P', 'Pendente')], default='V', max_length=10),
        ),
    ]
