# Generated by Django 5.1.5 on 2025-01-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0004_alter_servico_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='cidade',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
