# Generated by Django 5.1.5 on 2025-01-31 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_vendedores', '0003_alter_listavendedores_comissao_venda'),
        ('servico', '0005_servico_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='vendedor',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, to='lista_vendedores.listavendedores'),
            preserve_default=False,
        ),
    ]
