# Generated by Django 5.1.5 on 2025-01-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_vendedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listavendedores',
            name='Telefone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='listavendedores',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
