# Generated by Django 5.1.5 on 2025-01-31 16:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_vendedores', '0002_alter_listavendedores_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listavendedores',
            name='comissao_venda',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
