# Generated by Django 5.2.4 on 2025-07-14 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("servico", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcompanhamentoDespesasProjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=150)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_compra", models.DateField(auto_now_add=True)),
                ("observacao", models.CharField(blank=True, max_length=350, null=True)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servico.servico",
                    ),
                ),
            ],
        ),
    ]
