# Generated by Django 5.2.4 on 2025-07-14 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ListaVendedores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, unique=True)),
                ("Telefone", models.CharField(max_length=15, unique=True)),
                ("pix", models.CharField(max_length=15)),
                ("comissao_venda", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="VendaMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.CharField(max_length=15)),
                ("ano", models.IntegerField()),
                (
                    "total_vendas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_comissao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lista_vendedores.listavendedores",
                    ),
                ),
            ],
            options={
                "unique_together": {("vendedor", "mes", "ano")},
            },
        ),
    ]
