# Generated by Django 5.1.5 on 2025-01-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaVendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('Telefone', models.CharField(max_length=15)),
                ('pix', models.CharField(max_length=15)),
                ('comissao_venda', models.CharField(max_length=15)),
            ],
        ),
    ]
