# Generated by Django 5.1.5 on 2025-02-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_vendedores', '0003_alter_listavendedores_comissao_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listavendedores',
            name='comissao_venda',
            field=models.IntegerField(default=0),
        ),
    ]
