# Generated by Django 5.1.5 on 2025-02-25 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_vendedores', '0004_alter_listavendedores_comissao_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('total_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_comissao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista_vendedores.listavendedores')),
            ],
            options={
                'unique_together': {('vendedor', 'mes', 'ano')},
            },
        ),
    ]
