# Generated by Django 5.1.5 on 2025-02-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_vendedores', '0005_vendamensal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendamensal',
            name='mes',
            field=models.CharField(max_length=15),
        ),
    ]
