name: Deploy caoa

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 195.200.7.16 >> ~/.ssh/known_hosts  # Substitua pelo IP real ou domínio

      - name: Fazer deploy
        run: |
          ssh root@195.200.7.16 "
            cd /caminho/do/seu/projeto &&
            git pull origin main &&
            source /caminho/do/projeto/venv/bin/activate &&  # Ajuste para o caminho correto
            pip install -r requirements.txt &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            systemctl restart gunicorn  # Ou outro serviço
          "

