name: Deploy caoa

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H seu-servidor.com >> ~/.ssh/known_hosts

      - name: Fazer deploy
        run: |
          ssh usuario@seu-servidor.com "
            cd /caminho/do/seu/projeto &&
            git pull origin main &&
            source venv/bin/activate &&  # Se usar virtualenv
            pip install -r requirements.txt &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            systemctl restart gunicorn  # Ou outro serviço
          "
