name: Deploy Django

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 195.200.7.16 >> ~/.ssh/known_hosts

      - name: Testar conexão SSH
        run: ssh -o StrictHostKeyChecking=no root@195.200.7.16 "echo 'Conexão SSH funcionando!'"

      - name: Deploy via SSH
        run: |
          ssh root@195.200.7.16 << 'EOF'
            cd ~/caoa_eng &&
            git pull origin main
          EOF



